channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - python ==3.6
  - pip
  - pytest
  - pytest-runner
  - docker-py >=3.0
  - pep8
  - pytest-cookies >=0.4.0
  - pyflakes
  - snakemake ==5.13.0
  - urllib3
